{
 "title": "django",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "django_http_requests_total_by_view_transport_method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(django_http_requests_total_by_view_transport_method_total{view!=\"prometheus-django-metrics\"}[30s])) by(method, view)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{view}}/{{method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "django_http_responses_total_by_status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total{status=\"200\"}",
     "legendFormat": "status=200"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"404\"}",
     "legendFormat": "status=\"404\""
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"302\"}",
     "legendFormat": "status=\"302\""
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"500\"}",
     "legendFormat": "status=\"500\""
    }
   ]
  },
  {
   "title": "django_http_exceptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "django_http_exceptions", "legendFormat": "exceptions_total_by_view" },
    {
     "expr": "job:django_http_exceptions_total_by_type_sum_rate30s",
     "legendFormat": "exceptions_total_by_type"
    }
   ]
  },
  {
   "title": "Latency (99.9th percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:django_http_requests_latency_including_middlewares_seconds_quantile_rate30s_quantile_50",
     "legendFormat": "job:django_http_requests_latency_including_middlewares_seconds:quantile_rate30s{quantile=\"50\"}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[5m])) by (job, le))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "quantile=\"50\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[5m])) by (job, le))",
     "legendFormat": "quantile=\"95\""
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[5m])) by (job, le))",
     "legendFormat": "quantile=\"99\""
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[5m])) by (job, le))",
     "legendFormat": "quantile=\"99.9\""
    }
   ]
  }
 ]
}