# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_fr', models.CharField(max_length=25, null=True)),
                ('name_es', models.CharField(max_length=25, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=25)),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('image', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_fr', models.CharField(max_length=25, null=True)),
                ('name_es', models.CharField(max_length=25, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('title_en', models.CharField(max_length=25, null=True)),
                ('title_fr', models.CharField(max_length=25, null=True)),
                ('title_es', models.CharField(max_length=25, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=25)),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('image', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_fr', models.CharField(max_length=25, null=True)),
                ('name_es', models.CharField(max_length=25, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('job_title', models.TextField()),
                ('job_title_en', models.TextField(null=True)),
                ('job_title_fr', models.TextField(null=True)),
                ('job_title_es', models.TextField(null=True)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('intro_url', models.URLField()),
                ('intro_url_en', models.URLField(null=True)),
                ('intro_url_fr', models.URLField(null=True)),
                ('intro_url_es', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_fr', models.CharField(max_length=25, null=True)),
                ('name_es', models.CharField(max_length=25, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('image', models.URLField()),
            ],
        ),
    ]
