# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='job_title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_title_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_title_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='summary_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='summary_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='summary_fr',
            field=models.TextField(null=True),
        ),
    ]
