# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_interest_membership_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_fr',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='summary_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='summary_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='summary_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_fr',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='summary_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='summary_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='summary_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_fr',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='name_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='name_fr',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_es',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
