# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20170613_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 6, 13, 17, 33, 44, 690540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='intro_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='intro_url_en',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='intro_url_es',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='intro_url_fr',
            field=models.URLField(null=True),
        ),
    ]
