# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('icon', models.URLField()),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('image', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
