# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(),
        ),
    ]
