# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170610_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
