# Generated by Django 3.0.4 on 2020-04-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('category', models.TextField()),
                ('category_en', models.TextField(null=True)),
                ('category_fr', models.TextField(null=True)),
                ('category_es', models.TextField(null=True)),
                ('logo', models.TextField()),
                ('github', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
